name: Build and Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
